### ISSUE TITLE
bus01: Crear modelo de dato de usuario y endpoints

### ISSUE THREAD

**Issue by etomedina** [etomedina/ReparaHub-API-back-end#3]
- [x] Crear modelo de datos para usuario-cliente
- [x] Implementar endpoint para crear el usuario-cliente "registro_usuario" metodo "POST".

``` recibe: { email: string, // "tulio_lara@gmail.com", password: string(10 caracteres), // "soyBry4nMC" }```

**Comment by telara2801** [comment]
##DATABASE MODEL V0.2
![image](https://user-images.githubusercontent.com/66022636/159616466-ca8d408f-e0a7-4abf-87ad-b017e9454dd5.png)

**Comment by telara2801** [comment]
Database model after the change reaquest requesten on daily meeting
